var gvjs_Z3="linktable",gvjs__3="sankey.link.color.focused",gvjs_una="sankey.link.color.selected",gvjs_vna="sankey.link.color.unfocused",gvjs_wna="sankey.link.color.unselected",gvjs_03="sankey.node.color.focused",gvjs_xna="sankey.node.color.selected",gvjs_yna="sankey.node.color.unfocused",gvjs_zna="sankey.node.color.unselected",gvjs_13="sankey.node.label.focused",gvjs_Ana="sankey.node.label.selected",gvjs_Bna="sankey.node.label.unfocused",gvjs_Cna="sankey.node.label.unselected",gvjs_23="unique";
function gvjs_33(){}gvjs_m(gvjs_33,gvjs_cn);gvjs_33.prototype.Sb=function(a){try{this.Ic(a)}catch(b){return!1}return!0};
gvjs_33.prototype.Ic=function(a){if(Array.isArray(a)){var b=a;a=gvjs_dn(b[0]);b=gvjs_dn(b[1]);var c=a.Z();if(3>c)throw Error("Invalid linkTable format: must have at least 3 columns.");this.jb(gvjs_Z3,a,0,gvjs_f);this.jb(gvjs_Z3,a,1,gvjs_f);this.jb(gvjs_Z3,a,2,gvjs_f);var d=null,e=null,f=null,g=3;3<c&&""==a.Yh(3)&&(this.jb(gvjs_Z3,a,3,gvjs_f),d=3,g=4);for(c=g;c<a.Z();++c)g=a.Yh(c),g==gvjs_Md&&null===e?(e=c,this.jb(gvjs_Z3,a,c,gvjs_j)):g==gvjs_Sd&&null===f&&(f=c,this.jb(gvjs_Z3,a,c,gvjs_j));c=b.Z();
if(1!==c&&2!==c)throw Error("Invalid nodeTable format: must have 1 or 2 columns.");this.jb("nodetable",b,0,gvjs_j);2===c&&this.jb("nodetable",b,1,gvjs_j);g=[];for(var h=[],k=b.ca(),l=0,m=a.ca();l<m;++l){var n=a.getValue(l,0),p=a.getValue(l,1);if(n>=k||p>=k)throw Error("Invalid linkTable row: source and target nodes must be in the range 0 to "+(k-1)+".");var q=a.getValue(l,2),r=null,t=null,u=null;null!=e&&(r=a.getStringValue(l,e));null!=d&&(t=a.getValue(l,d));null!=f&&(u=a.getValue(l,f));h.push({source:n,
target:p,value:q,style:r,tooltip:u,opacity:t})}a=0;for(e=b.ca();a<e;++a)g.push({name:b.getValue(a,0),Fb:2===c?b.getValue(a,1):""});return{links:h,nodes:g,vF:f,vR:d}}a=gvjs_dn(a);c=a.Z();if(3>c)throw Error("Invalid data table format: must have at least 3 columns.");this.jb(gvjs_ep,a,0,gvjs_j);this.jb(gvjs_ep,a,1,gvjs_j);this.jb(gvjs_ep,a,2,gvjs_f);f=d=b=null;e=3;3<c&&""==a.Yh(3)&&(this.jb(gvjs_ep,a,3,gvjs_f),b=3,e=4);for(c=e;c<a.Z();++c)e=a.Yh(c),e==gvjs_Md&&null===d?(d=c,this.jb(gvjs_ep,a,c,gvjs_j)):
e==gvjs_Sd&&null===f&&(f=c,this.jb(gvjs_ep,a,c,gvjs_j));c=new Map;e=[];g=[];h=0;for(k=a.ca();h<k;++h)l=a.getStringValue(h,0),m=a.getStringValue(h,1),l=gvjs_Dna(c,e,l),m=gvjs_Dna(c,e,m),n=a.getValue(h,2),p=null,null!=d&&(p=a.getStringValue(h,d)),q=null!=f?a.getValue(h,f):null,r=null,null!=b&&(r=a.getValue(h,b)),g.push({source:l,target:m,value:n,style:p,tooltip:q,opacity:r});return{links:g,nodes:e,vF:f,vR:b}};
function gvjs_Dna(a,b,c){if(a.has(c))return a.get(c);a.set(c,b.length);b.push({name:c,Fb:""});return b.length-1}gvjs_33.prototype.jb=function(a,b,c,d,e){if(!gvjs_gn(b,c,d,e))throw Error(gvjs_ns+a+": column #"+c+gvjs_ba+d+"'.");};function gvjs_43(a,b){gvjs_VQ.call(this);this.pa=null;this.Ti=b;this.II=null;this.C2=new gvjs_C;this.B2=new gvjs_C;this.ua=a}gvjs_m(gvjs_43,gvjs_VQ);
gvjs_43.prototype.BB=function(a){var b=[],c=gvjs_IK(a.$a());this.pa&&(this.ua.kg?gvjs_uI(this.pa,this.Ti.getContainer()):b.push(new gvjs_UQ(gvjs_wI(this.pa,c).j(),new gvjs_KK(gvjs_UP),gvjs_Sd)),this.pa=null);var d=new gvjs_C,e=new gvjs_C,f=new gvjs_C,g=new gvjs_C;null!=this.II&&gvjs_Ena(this,this.II,e,d);gvjs_Cy(this.B2,function(n){var p=this.ua.paths[n];f.add(n);g.add(p.qY);g.add(p.w4)},this);gvjs_Cy(this.C2,function(n){gvjs_Fna(this,n,f,g)},this);var h=0<g.tb(),k=0<d.tb();gvjs_s(this.ua.labels,
function(n,p){var q=n.styles.Kd,r=gvjs__P;g.contains(p)&&d.contains(p)?(q=n.styles.LK,r=gvjs_Gs):d.contains(p)?q=n.styles.focused:g.contains(p)?(q=n.styles.selected,r=gvjs_Gs):h&&k?q=n.styles.ML:h?q=n.styles.LL:k&&(q=n.styles.KL);n=c.Co(n.text,n.x,n.y,n.width,n.angle,n.cA,n.dA,q);p=gvjs_MK(gvjs_MK(new gvjs_KK(gvjs_es),gvjs_vs,p),gvjs_xs,gvjs_bd);b.push(new gvjs_UQ(n,p,r))},this);gvjs_s(this.ua.aS,function(n,p){var q=gvjs_MK(gvjs_MK(gvjs_LK(p),gvjs_xs,"node"),"NAME",this.ua.labels[p].text),r=n.Vb.Kd,
t=gvjs__P;g.contains(p)&&d.contains(p)?(r=n.Vb.LK,t=gvjs_4P):d.contains(p)?r=n.Vb.focused:g.contains(p)?(t=gvjs_4P,r=n.Vb.selected):h&&k?r=n.Vb.ML:h?r=n.Vb.LL:k&&(r=n.Vb.KL);n=c.Uj(n.x,n.y,n.width,n.height,r);b.push(new gvjs_UQ(n,q,t))},this);var l=0<f.tb(),m=0<e.tb();gvjs_s(this.ua.paths,function(n,p){var q=gvjs_MK(gvjs_MK(new gvjs_KK(gvjs_us),gvjs_vs,p),gvjs_xs,"link"),r=n.Vb.Kd,t=gvjs_Cw;f.contains(p)&&e.contains(p)?(r=n.Vb.LK,t=gvjs_4P):e.contains(p)?r=n.Vb.focused:f.contains(p)?(t=gvjs_4P,r=
n.Vb.selected):l&&m?r=n.Vb.ML:l?r=n.Vb.LL:m&&(r=n.Vb.KL);n=c.Dc(n.Fc,r);b.push(new gvjs_UQ(n,q,t))},this);return b};gvjs_43.prototype.Xb=function(){return this.ua.size};function gvjs_Ena(a,b,c,d){var e=b.sb.SUBTYPE;null!=a.II&&(b=a.II.sb.ROW_INDEX,"node"===e?gvjs_Fna(a,b,c,d):"link"===e&&(a=a.ua.paths[b],c.add(b),d.add(a.qY),d.add(a.w4)))}function gvjs_Fna(a,b,c,d){d.add(b);gvjs_s(a.ua.Isa[b].La(),function(e){c.add(e);e=this.ua.paths[e];d.add(e.qY);d.add(e.w4)},a)}
gvjs_43.prototype.Am=function(a,b,c){switch(b.type){case gvjs_Sd:a.type()===gvjs_us?this.gz(a,c):a.type();break;case gvjs_Cu:a.type()===gvjs_us?this.II=c?a:null:a.type();break;case gvjs_i:a.type()===gvjs_us&&(b=a.sb.ROW_INDEX,"node"===a.sb.SUBTYPE?c?this.C2.add(b):this.C2.remove(b):c?this.B2.add(b):this.B2.remove(b))}};
gvjs_43.prototype.gz=function(a,b){this.Ti.clear();this.pa=null;if(b){b=a.sb.SUBTYPE;var c=a.sb.ROW_INDEX;a=this.ua.size;a=new gvjs_A(0,a.width,a.height,0);var d=null,e=null,f=null,g=null;"node"==b?(g=this.ua.aS[c],e=new gvjs_u(g.x,g.y),f=gvjs_Hz(e,new gvjs_u(-1,1))):"link"==b&&(g=this.ua.paths[c],b=g.Fc,e=new gvjs_u((b.Fc[0].data.x+b.Fc[1].data.x)/2,(b.Fc[0].data.y+b.Fc[1].data.y)/2),f=gvjs_Hz(e,new gvjs_u(-1,1)));g.tooltip&&e&&f&&(g.tooltip.content&&this.ua.kg?d={html:gvjs_vg(gvjs_Sb,{"class":gvjs_Su},
gvjs_XA(g.tooltip.content)),ON:g.tooltip.$h,gK:f,anchor:e,HG:a,spacing:20,margin:5}:(b={entries:[]},g.tooltip.content?b.entries.push(gvjs_mE(g.tooltip.content,this.ua.Lp)):g.tooltip.title&&(b.entries.push(gvjs_mE(g.tooltip.title,this.ua.Lp)),b.entries.push(gvjs_mE(g.tooltip.exa.toString(),this.ua.Lp,g.tooltip.cxa,this.ua.Lp)),g.tooltip.lda&&g.tooltip.mda&&b.entries.push(gvjs_mE(g.tooltip.mda.toString(),this.ua.Lp,g.tooltip.lda,this.ua.Lp))),d=gvjs_pE(b,this.ua.Gc,!1,e,a,f,void 0,this.ua.kg)));d&&
(this.pa=d)}};var gvjs_Gna={NONE:gvjs_e,oBa:"source",ABa:"target",$za:gvjs_zp},gvjs_Hna={PU:gvjs_It,NBa:gvjs_23};function gvjs_Ina(a,b,c,d){this.W=a;this.m=b;this.be=c;this.bb=d;this.fb=(new gvjs_33).Ic(a);this.msa=gvjs_F(b,"sankey.iterations");this.Gba=gvjs_Ly(b,"sankey.link.color");gvjs_Ly(b,"sankey.link.focused");gvjs_Ly(b,"sankey.link.unfocused");a=b.cD("sankey.link.colors");this.Hba=null==a?null:gvjs_t(a,function(e){return gvjs_Th(gvjs_Oh(e).hex)});this.xD=gvjs_D(b,"sankey.link.colorMode",gvjs_e,gvjs_Gna);this.vma=gvjs_F(b,"sankey.link.defaultOpacity",this.Gba.ff);this.pca=gvjs_F(b,"sankey.link.minOpacity",
.2);this.Xsa=gvjs_F(b,"sankey.link.maxOpacity",.6);a=b.cD("sankey.node.colors");this.Jta=null==a?null:gvjs_t(a,function(e){return gvjs_Th(gvjs_Oh(e).hex)});this.Ita=gvjs_Ly(b,"sankey.node.color");this.O0=gvjs_D(b,"sankey.node.colorMode",gvjs_23,gvjs_Hna);this.HP=gvjs_E(b,gvjs_6u,!1);this.Ye=gvjs_My(b,"sankey.node.label");this.qba=gvjs_F(b,"sankey.node.labelPadding");this.Kta=gvjs_F(b,"sankey.node.nodePadding");this.Lta=gvjs_F(b,"sankey.node.width")}
gvjs_Ina.prototype.rh=function(){var a=gvjs_Jna(this);gvjs_Kna(a);var b=this.Ye.fontSize;b=d3.sankey().nodeWidth(this.Lta).nodePadding(this.Kta).size([this.bb.width,this.bb.height-b/2]).iterations(this.msa);b(a);gvjs_Lna(a.nodes);var c=new gvjs_7Q(this.HP,this.Jta),d=new gvjs_7Q(this.HP,this.Hba),e=[],f=[],g=[],h=null==this.Hba&&this.O0===gvjs_23;gvjs_s(a.nodes,function(w,x){w.idx=x;c.Eu(this.O0===gvjs_It?w.Fb:String(x));h||("source"===this.xD&&0<w.sourceLinks.length||"target"===this.xD&&0<w.targetLinks.length||
this.xD===gvjs_zp)&&d.Eu(String(x))},this);var k=null;null!=this.fb.vF&&(k=this.fb.vF);var l=this.W.Ca(2);null===l&&(l="Width");var m=null;null!=this.fb.vR&&(m=this.W.Ca(this.fb.vR),null===m&&(m="Opacity"));var n=Infinity,p=-Infinity;null!=this.fb.vR&&gvjs_s(a.links,function(w){null!=w.opacity&&(n=Math.min(n,w.opacity),p=Math.max(p,w.opacity))},this);var q=c.td(),r=h?q:d.td();gvjs_s(a.links,function(w,x){w.idx=x;var y=this.vma;null!=w.opacity&&p>n&&(y=this.pca+(w.opacity-n)/(p-n)*(this.Xsa-this.pca));
var z=this.Gba.clone();z.zf(y);y="source"===this.xD?String(w.source.idx):"target"===this.xD?String(w.target.idx):null;null!=y?z.bf(r.Jq(y)):this.xD===gvjs_zp&&gvjs_Tx(z,{eg:r.Jq(String(w.source.idx)),Gf:r.Jq(String(w.target.idx)),Kn:1,Ln:1,x1:gvjs_Lo,y1:0,x2:gvjs_Mo,y2:0,eo:!0,Cp:!1});y=w.style;null!=y&&(y=gvjs_SH(y),null!=y&&(y=new gvjs_ji([y]),z.bf(gvjs_Jy(y,[gvjs_np,gvjs_lp],z.nb())),z.zf(gvjs_Iy(y,gvjs_op,z.ff)),z.gd(gvjs_Jy(y,[gvjs_4p,gvjs_1p],z.Af)),gvjs_Rx(z,gvjs_Iy(y,gvjs_5p,z.Yi)),z.yl(gvjs_F(y,
gvjs_6p,z.Ub))));x=null!=k&&w.tooltip?{$h:!(!this.W.getProperty(x,k,gvjs_dv)&&!this.W.Xe(k,gvjs_dv)),content:w.tooltip}:{title:w.source.name+" -> "+w.target.name,cxa:l,exa:w.value,lda:m,mda:w.opacity};y=new gvjs_hy;var A=w.source.x0+(w.source.x1-w.source.x0),B=w.source.y0+(w.y0-w.source.y0-w.width/2),F=w.target.x0,C=w.target.y0+(w.y1-w.target.y0-w.width/2),H=(F-A)/3;y.move(A,B);y.mo(A+H,B,A+2*H,C,F,C);y.va(F,C+w.width);y.mo(A+2*H,C+w.width,A+H,B+w.width,A,B+w.width);y.close();A=null==this.m.ea(gvjs_una)?
z.clone().zf(.8):gvjs_Ly(this.m,gvjs_una,z);B=null==this.m.ea(gvjs__3)?z.clone().zf(.8):gvjs_Ly(this.m,gvjs__3,z);F=gvjs_Ly(this.m,gvjs_vna,z);C=null==this.m.ea(gvjs_wna)?z.clone().zf(.2):gvjs_Ly(this.m,gvjs_wna,z);H=gvjs_Ly(this.m,gvjs__3,A);var G=gvjs_Ly(this.m,gvjs_vna,C);e.push({Vb:{Kd:z,selected:A,focused:B,KL:F,LL:C,LK:H,ML:G},tooltip:x,qY:w.source.idx,w4:w.target.idx,Fc:y})},this);var t=this.bb.width,u=b.nodeWidth(),v={};gvjs_s(a.nodes,function(w,x){var y=new gvjs_C;gvjs_s(w.sourceLinks,function(J){y.add(J.idx)},
this);gvjs_s(w.targetLinks,function(J){y.add(J.idx)},this);v[x]=y;x=w.x0<t/2;var z=this.Ita.clone();z.bf(q.Jq(this.O0===gvjs_It?w.Fb:String(w.idx)));z.gd(z.nb(),0);var A=null==this.m.ea(gvjs_xna)?z.clone().zf(1):gvjs_Ly(this.m,gvjs_xna,z),B=null==this.m.ea(gvjs_03)?z.clone().zf(1):gvjs_Ly(this.m,gvjs_03,z),F=gvjs_Ly(this.m,gvjs_yna,z),C=null==this.m.ea(gvjs_zna)?z.clone().zf(.2):gvjs_Ly(this.m,gvjs_zna,z),H=gvjs_Ly(this.m,gvjs_03,A),G=gvjs_Ly(this.m,gvjs_yna,C);g.push({Vb:{Kd:z,selected:A,focused:B,
KL:F,LL:C,LK:H,ML:G},x:w.x0,y:w.y0,tooltip:w.tooltip,width:u,height:w.y1-w.y0});z=null==this.m.ea(gvjs_Ana)?gvjs_yy((new gvjs_Ay(this.Ye)).setOpacity(.8),!0):gvjs_My(this.m,gvjs_Ana,this.Ye);A=null==this.m.ea(gvjs_13)?gvjs_yy((new gvjs_Ay(this.Ye)).setOpacity(.8),!0):gvjs_My(this.m,gvjs_13,this.Ye);B=gvjs_My(this.m,gvjs_Bna,this.Ye);F=null==this.m.ea(gvjs_Cna)?(new gvjs_Ay(this.Ye)).setOpacity(.4):gvjs_My(this.m,gvjs_Cna,this.Ye);C=gvjs_My(this.m,gvjs_13,z);H=gvjs_My(this.m,gvjs_Bna,F);f.push({angle:0,
cA:x?gvjs_1:gvjs_T,dA:gvjs__,styles:{Kd:this.Ye,selected:z,focused:A,KL:B,LL:F,LK:C,ML:H},text:w.name,width:0,x:x?w.x0+u+this.qba:w.x0-this.qba,y:w.y0+(w.y1-w.y0)/2})},this);return{labels:f,paths:e,aS:g,Isa:v,nodeWidth:u,size:this.bb,Gc:this.be,kg:gvjs_E(this.m,gvjs_kx,!0),Lp:gvjs_My(this.m,gvjs_mx)}};function gvjs_Jna(a){a=a.fb;return{nodes:a.nodes,links:a.links}}
function gvjs_Kna(a){var b=gvjs_t(a.nodes,function(e,f){return{index:f,rga:[]}});gvjs_s(a.links,function(e){b[e.source].rga.push(b[e.target])});a=new gvjs_C(b);for(var c=new gvjs_C,d=0;0<a.tb();){if(d>b.length)throw a=gvjs_t(a.La(),function(e){return e.index}).join(","),Error("Cycle found in rows: "+a);gvjs_s(a.La(),function(e){gvjs_s(e.rga,function(f){c.add(f)})});a=c;c=new gvjs_C;d++}}
function gvjs_Lna(a){gvjs_s(a,function(b){gvjs_Ve(b.targetLinks,function(c,d){function e(f){return(f.target.y0-(f.source.y0+(f.y0-f.source.y0-f.width/2)))/(f.target.x0-f.source.x0)}return e(d)-e(c)})});gvjs_s(a,function(b){var c=0;gvjs_s(b.targetLinks,function(d){d.y1=c+d.target.y0+d.width/2;c+=d.width})})};function gvjs_53(a){gvjs_WK.call(this,a)}gvjs_m(gvjs_53,gvjs_WK);gvjs_=gvjs_53.prototype;gvjs_.Eq=function(){return{NAME:gvjs_Yv}};
gvjs_.Mf=function(){return{backgroundColor:{fill:gvjs_Ix,stroke:gvjs_0o,strokeWidth:10,strokeOpacity:.2},tooltip:{isHtml:!1,textStyle:{fontName:gvjs_Uo,fontSize:16,color:gvjs_0o}},sankey:{iterations:32,link:{colorMode:gvjs_e,color:{fill:"#aaa",fillOpacity:.8,stroke:gvjs_e},defaultOpacity:.6,minOpacity:.2,maxOpacity:.6},node:{colorMode:gvjs_23,color:{fill:gvjs_0o,fillOpacity:.8},label:{fontName:gvjs_Dw,fontSize:10,color:gvjs_zr,bold:!1,italic:!1},labelPadding:6,nodePadding:10,width:10,interactivity:!1,
selectionMode:gvjs_Zp}}}};gvjs_.Bo=function(a,b){return new gvjs_43(a,b)};gvjs_.$m=function(a,b,c,d){return new gvjs_Ina(a,b,c,d)};gvjs_.iq=function(a,b,c,d){a=gvjs_WK.prototype.iq.call(this,a,b,c,d);a.gu([gvjs_Cw,gvjs__P,gvjs_Bw,gvjs_4P,gvjs_Hs,gvjs_Gs,gvjs_Sd]);return a};
gvjs_.Gs=function(a){var b=gvjs_E(a,"sankey.node.interactivity",!1),c=[new gvjs_QQ([new gvjs_KK(gvjs_us)]),new gvjs_TQ([new gvjs_KK(gvjs_us)])];b&&c.push(new gvjs_SQ([gvjs_MK(new gvjs_KK(gvjs_us),gvjs_xs,"node")]));gvjs_E(a,"sankey.link.interactivity",!1)&&(a=gvjs_D(a,"sankey.link.selectionMode",gvjs_Zp)===gvjs_Zp,c.push(new gvjs_RQ([gvjs_MK(new gvjs_KK(gvjs_us),gvjs_xs,"link")],a)));return c};gvjs_o(gvjs_Rc,gvjs_53,void 0);gvjs_53.prototype.draw=gvjs_53.prototype.draw;gvjs_53.prototype.setSelection=gvjs_53.prototype.setSelection;gvjs_53.prototype.getSelection=gvjs_53.prototype.getSelection;gvjs_53.prototype.clearChart=gvjs_53.prototype.Lb;gvjs_53.prototype.getContainer=gvjs_53.prototype.getContainer;
